const teamSchema = {
  id: {
    type: 'uuid',
    required: false, // Auto-generated by Supabase
  },
  name: {
    type: 'varchar',
    length: 255,
    required: true,
  },
  logo: {
    type: 'varchar',
    length: 500,
    required: false,
  },
  region: {
    type: 'varchar',
    length: 100,
    required: false,
  },
  description: {
    type: 'text',
    required: false,
  },
  creator_id: {
    type: 'uuid',
    required: true,
  },
  created_at: {
    type: 'timestamp',
    required: false, // Auto-generated by Supabase
  },
  updated_at: {
    type: 'timestamp',
    required: false, // Auto-generated by Supabase
  },
};

module.exports = teamSchema;
